### ISSUE TITLE
migrate to new architecture

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-store-server#32]
part of https://github.com/hoodiehq/hoodie/issues/458

- [x] rename to `hoodie-store-server`
- [x] in `package.json`, set `"name"` to `"@hoodie/store-server"`, and add `"publishConfig": {"access": "public"}`
- [x] find `hoodie-store-server` and replace with `hoodie-store-server`
- [x] do commits as in https://github.com/hoodiehq/hoodie-log/issues/31

Once merged

- [x] deprecate `hoodie-server-store` in the npm registry
- [x] enable coveralls for new repo name (run `COVERALLS_REPO_TOKEN=... npm run coverage`, then on coveralls.io require `100%` coverage for success)
- [x] update branch protection: re-enable coveralls

**Comment by finnp** [comment]
Published as https://www.npmjs.com/package/@hoodie/store-server
